version: '3.3'

services:
  nginx:
    container_name: laravel-quick-start-nginx
    build:
      context: docker/nginx
    restart: on-failure
    networks:
      - app
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
      - app
    ports:
      - "${DOCKER_NGINX_HTTP_PORT}:80"
      - "${DOCKER_NGINX_HTTPS_PORT}:443"
  app:
    container_name: laravel-quick-start-app
    build:
      context: docker/app
    volumes:
      - ./:/var/www:delegated
    restart: on-failure
    command: docker-php-entrypoint php-fpm
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_connect_back=0 remote_enable=1 log=/tmp/xdebug.log log_level=0"
      PHP_IDE_CONFIG: "serverName=${APP_NAME}"
      IDE_KEY: PHPSTORM
      COMPOSER_HOME: /tmp/home/composer
      COMPOSER_CACHE_DIR: /tmp/home/composer_cache
    depends_on:
      - db
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    container_name: laravel-quick-start-db
    build:
      context: docker/db
    restart: on-failure
    working_dir: /var/www/scripts
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/var/www:delegated
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app
    ports:
      - "${DOCKER_PGSQL_PORT}:5432"
volumes:
  postgresdata:
networks:
  app:
    driver: bridge
